### ISSUE TITLE
Format model data before posting to api?

### ISSUE THREAD

**Issue by dylanbathurst** [zohararad/sails-rest#15]
Is it currently possible to format the json object in a certain way before making the POST request to the api? 

In sails/sails-rest when I create a new user, the body of the create method looks like

```javascript
{
    "first_name": "Stanley",
    "last_name": "Ipkiss"
}
```

The api that I'm connecting to with sails-rest wants a more explicit format for new users though, such as

```javascript
{
"user": {
    "first_name": "Stanley",
    "last_name": "Ipkiss"
}
}
```

Is there a way to add this explicit wrapper key to the body before sending to the api?

**Comment by zohararad** [comment]
@dylanbathurst please check out [v0.1.0-waterline-v0.10](https://github.com/zohararad/sails-rest/tree/v0.1.0-waterline-v0.10) which is a complete re-write of the adapter, with support for before and after hooks that let you modify data before sending it.

Would love to hear what you think.
