### ISSUE TITLE
using another sailsjs as rest backend

### ISSUE THREAD

**Issue by jacqueslareau** [zohararad/sails-rest#32]
I want to use another sailjs app as a rest connection. When trying to find records using the query language, it doesn't work. It deserialize the where object.

So a query to app A:

```
/api/account?where={"name":{"contains":"A"}}&skip=20&limit=30
```
creates a request on app B as:

```
/api/account?name=&skip=20&limit=30
```
EDIT: the second issue was a bug somewhere else

**Comment by zohararad** [comment]
@jacqueslareau the adapter doesn't support Waterline's query language since it doesn't work against a database. I suggest trying to modify the `where` parameter into a query string that your backend can understand

**Comment by jacqueslareau** [comment]
@zohararad Thanks for your reply.

I'm not sure I understand. There where is generated by the client and works fine with a model that is using sails-mysql adapter. Switching the model to use the sails-rest adapter should work as is? I can adjust the where parameter, on the client, depending on which adapter I'm using, but that takes away some abstraction.

Another approach is to replace the auto generated API to a manual one and rewrite the where query. That should also work but doesn't leverage sailsjs's main feature.

I forked your repo, added a JSON.stringify to the where parameter and everything works as expected (for now). But I'm just testing stuff and I may be completely wrong.

**Comment by zohararad** [comment]
@jacqueslareau Stringifying the JSON where parameter is fine but please take into account that not all REST apis were born equal - maybe someone might not need the query passed inside a where parameter? This is exactly why sails-rest doesn't work the same as normal DB adapters - there's no standard query language to translate to.

I suggest you try using the before callbacks to do any modifications you need on the data you're sending instead of simply stringifying the where param.

Does that make more sense?

**Comment by jacqueslareau** [comment]
@zohararad And where are the before callbacks that I can use to do that?

**Comment by jacqueslareau** [comment]
@zohararad But in the long run, what about a plugin system for specific rest endpoints? We could have sails-rest-sails that would adjust the request to support the query language. Or maybe it's better to have a separate adapter for each? We could have a sails-sails adapter? What do you think?

**Comment by zohararad** [comment]
I actually think that 2 or 3 are more inline with keeping things simple, but a PR for 1 will be happily accepted.

I don't want to complicate things with plugins - I realise sails-rest isn't perfect, but if you're in control of that API you're calling, then modifying it to accept your request without knowledge of the Waterline query language is in my opinion a plus.
