### ISSUE TITLE
add documentation on query function

### ISSUE THREAD

**Issue by jacqueslareau** [zohararad/sails-rest#34]
I open this issue to not forget to add documentation.

- With a function, you are 100% responsible for creating the query parameters
- signature: config, collectionName, methodName, options
- a note on default behavior

**Comment by zohararad** [comment]
@jacqueslareau any chance of getting a PR for this?

**Comment by jacqueslareau** [comment]
@zohararad Thanks for the reminder! View PR #37

**Comment by zohararad** [comment]
Perfect, thanks a lot
