### ISSUE TITLE
Populate behave differently on insert

### ISSUE THREAD

**Issue by Nutelac** [zohararad/sails-rest#43]
I have two models:

**User**
```
name: string
group: Group
```

**Group**
```
name: string
```

When I send request:
```
path: '/users'
method: POST
data: {
  name: 'John Doe',
  group: 1
}
```

Response is:
```json
{
  "name" : "John Doe",
  "group": 1
}
```

But i think it should be:
```json
{
  "name" : "John Doe",
  "group": {
    "id": 1,
    "name": "fuzz"
  }
}
```

Why is `insert` the only action which not populate relationships? On every other action (`delete`, `update`) is `group` populated.

Thanks.

**Comment by zohararad** [comment]
sails-rest is a bit of a weird beast in that respect as it's not a real DB adapter. You can easily overcome this by modifying your response to include the relationship though, no?
