### ISSUE TITLE
Better Examples

### ISSUE THREAD

**Issue by jhawlwut** [zohararad/sails-rest#45]
So I'm having some issues trying to figure out the setup here.

I see this:
``` javascript
pathname: '/api/v1',      // base api path
resource: null,           // resource path to use (overrides model name)
action: null,             // action to use for the given resource ([resource]/run)
```
Do these pertain to my external API path, or would these define my internal SailsJS API?

For example, if I wanted to call the following from my external API
```terminal
curl -X POST http://localhost:9999/api/returnList
```

What would be the best way to implement this in a model / controller?

**Comment by zohararad** [comment]
These parameters are modelled after Rails' routing principles.

So your pathname should be `/api` your resource should be `returnList` and your action should be an empty string
