### ISSUE TITLE
How to pass an X-Forwarded-For header 

### ISSUE THREAD

**Issue by thatguy666** [zohararad/sails-rest#53]
I notice that there is a headers: {} config option but no documentation on how to define the header.
I've tried a literal string, and an array. Neither of these work.  Can you provide an example of passing an X-Forwarded-For header.

**Comment by zohararad** [comment]
@thatguy666 Did you use the master branch or v0.1.0?

On the v0.1.0 branch it should be as simple as:

```
{
  'X-Forwarded-For':'10.0.1.0'
}
```

Please check out [connection.js](https://github.com/zohararad/sails-rest/blob/v0.1.0-waterline-v0.10/lib/connection.js#L55)
