### ISSUE TITLE
handleResponse throwing exception in error case

### ISSUE THREAD

**Issue by davepreston** [zohararad/sails-rest#57]
Regarding v0.1.0-waterline-v0.10

```
function handleResponse(connection, err, res, cb) {
  runAfterHooks(connection, err, res);
  cb(err, res.body);    // <-- res may be undefined here.
}
```

if an error occurs res may be undefined. That causes a typeError: Cannot read property 'body' of undefined.

In my case I had an untrusted CERT so the superagent call failed.

**Comment by zohararad** [comment]
Good catch. Fixed!
