### ISSUE TITLE
Changing REST method on 0.1.0

### ISSUE THREAD

**Issue by wwhurley** [zohararad/sails-rest#58]
On 0.0.4 the configuration contained the method to use for the appropriate action. In there an equivalent for 0.1.0? I have an endpoint that uses PATCH instead of POST for updates.

**Comment by zohararad** [comment]
@wwhurley at the moment, there's no such option.

I can try and add this over the coming week or accept a PR if you have time to add it yourself.

Take a look at calls to `runBeforeHooks` inside `connection.js` - that's where the HTTP method is set. Ideally the config should contain a list of overrides per adapter action

**Comment by wwhurley** [comment]
I'm noticing that the setting of the req object is inside the .forEach loop. Is this intended?

**Comment by zohararad** [comment]
Thanks for that - looks good. See my comments please. Regarding setting the req object inside the forEach loop - good catch, but this should happen before the loop rather than after, so hooks have a chance to modify the request

**Comment by wwhurley** [comment]
Thanks. Also thanks for catching my error with "delete" and "del".
