### ISSUE TITLE
Branch v0.1.0 doesn't support pluralised resources

### ISSUE THREAD

**Issue by jamesjwarren** [zohararad/sails-rest#61]
Functionality to configure pluralisation of resources would be useful i.e. `Post` model could be configured to call `/posts` as per `0.0.x`.

**Comment by zohararad** [comment]
@jacqueslareau You can simply use your own before hooks to create the endpoint in question, no?

**Comment by jamesjwarren** [comment]
I see, thanks.

**Comment by jamesjwarren** [comment]
@zohararad this is a great module, I would love to see v0.1.0 reach release is there anything you need a hand with?

**Comment by zohararad** [comment]
@jamesjwarren thanks for the offer - things seem pretty stable for now. I want to wait a while longer before releasing to get a bit more feedback on edge cases though. Let's give it another week or two :)
