### ISSUE TITLE
Headers never get added to request

### ISSUE THREAD

**Issue by jamesjwarren** [zohararad/sails-rest#62]
Documentation suggests custom headers can be set in the connection config, however they never get applied.
```
rest: {
    ...
    headers: {
      'Some-Header': 'xyx'
    }
}
```

It looks like the `headers` property is not on `conn.connection` at this point https://github.com/zohararad/sails-rest/blob/v0.1.0-waterline-v0.10/lib/connection.js#L33

Further debugging suggests it is because the headers property is never set on `connections[connection.identity]`. Adding `config.headers = connection.headers || {};` in the registerConnection block appears to fix it.

**Comment by zohararad** [comment]
@jamesjwarren Good catch. Fixed
