### ISSUE TITLE
Difficult to use with paginated API responses

### ISSUE THREAD

**Issue by jamesjwarren** [zohararad/sails-rest#64]
I have found it difficult to use with paginated API responses. For example an API may return a response with additional meta data:
```json
{
  "items": [
    { "id": 1 },
    { "id": 2 }
  ],
  "pagination": {
    "total": 3,
    "limit": 2,
    "current": 1
  }
}
```

Currently it is possible to use after hooks to reformat this so waterline returns just the array of items `res.body.items`. However the pagination meta is then lost. 

### Potential Solution
I'm wondering if it would be possible to make the response handler configurable so the results array and meta could be returned separately.

I.e. could the `handleResponse` function be configured on a connection basis to make it possible to return something like `cb(err, res.body.items, res.body.pagination)`.
https://github.com/zohararad/sails-rest/blob/v0.1.0-waterline-v0.10/lib/connection.js#L72

In waterline this could then be used like:
```
Model.find()
  .exec(function(err, results, meta){
    // results is still an array
  });
```

Just an initial idea from my experience using this. Currently to keep the pagination meta intact I am having to return the entire object from the API which then gets wrapped in an array, which is messy and inconsistent with how data is returned from other resources. I know this is quite a specific use-case but I'm sure there may be others that could benefit from added flexibility.

> On further inspection it looks like the callback is restricted to `cb(err, models)` in waterline so this wouldn't work. Any further ideas are very welcome!

**Comment by zohararad** [comment]
I definitely see your point and it is a bit of a problem.

I can suggest one of the following:

* Create a global state object where each key is mapped to a request base-url (so without pagination params), and save the pagination data there
* Inject the current page and total results to each object in the res.body, which is dirtier in terms of schema, but cleaner in terms of implementation (via custom response handler)
* Add a count method to the connection or just call a /count endpoint yourself and get the total number of records

Does that help in any way?

**Comment by jamesjwarren** [comment]
The count method on the connection sounds like a good solution. In the short term I think I'll take on your seconds suggest and inject a pagination object into the first record. Thanks for the suggestions.
