### ISSUE TITLE
Error with response body not handled as an error

### ISSUE THREAD

**Issue by talbe1992** [zohararad/sails-rest#70]
in connection.js, the condition: 
if (res) {
        err = null;
      }

Means, that is there is a response, the response won't be handled as an error.
In our case, the db returns us an error, but with response body.
This condition made us get the response as 'success', although it's an error to catch.

Tal.

**Comment by zohararad** [comment]
@talbe1992 please look at my commit and let me know if OK, and I'll merge to master
