### ISSUE TITLE
Endpoint hook for custom routing

### ISSUE THREAD

**Issue by chadmetcalf** [zohararad/sails-rest#72]
We're making a hook that interprets things into our non-restful API.

The Sails endpoint:

``` javascript
/something/:id
```

passes the information that I need (model name, id, request method) through the controller, waterline, and the adapter to our hook.

But if I want to redirect for an endpoint like:

``` javascript
/something/:id/sub-somethings
```

I lose the `sub-somethings` information and cannot build my route.

Any ideas how to get that data?

**Comment by chadmetcalf** [comment]
It looks like that this might even be a waterline issue. It seems that the `/something/:id/sub-somethings` is being interpreted into: `something.find(:id).populate('sub-somethings')` instead of `sub-somethings.where('something': :id)`. I'll move the issue to the waterline repo if I'm off base her, what do you think?

**Comment by zohararad** [comment]
I agree, and in addition, if you feel like it, it might be a good idea to create a generic request method that simply exposes the underlying restify client. Care to send a PR?
