### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by dash-** [zohararad/sails-rest#75]
TypeError: Cannot read property 'body' of undefined
    at .../node_modules/sails-rest/lib/connection.js:86:16

To reproduce, take down the remote API and try to call it.  You will get this error.  Of course, you should get an error -- you just shouldn't get this error.

```javascript
 74 /**
 75  * Handle SuperAgent HTTP Response. Calls hook functions followed by Waterline callback.
 76  * @param {Object} connection - connection configuration object
 77  * @param {Error} err - response error object
 78  * @param {Response} res - SuperAgent HTTP Response object
 79  * @param {Function} cb - function to call with query results.
 80  */
 81 function handleResponse(connection, err, res, cb) {
 82   runAfterHooks(connection, err, res, function (errFromHooks) {
 83     if(errFromHooks) {
 84       return cb(errFromHooks);
 85     }
 86     cb(err, res.body);  // <-- Bug when there's an error and res is undefined
 87   });
 88 }
```

Maybe instead:
```javascript
if(err) {
  return cb(err);
}
cb(null, res.body);
```

Or:
```javascript
if(! res) {
  return cb(err);
}
cb(err, res.body);
```

**Comment by zohararad** [comment]
This is fixed on master. Which branch / version are you using?

**Comment by dash-** [comment]
0.1.0 - had done a `npm install sails-rest --save` on June 14th, 2016.
Just removed it from package.json, and re-issued the npm command, got the
same version.

You might consider doing a `npm publish` if 0.1.0 is outdated.

**Comment by zohararad** [comment]
Yeah.. master and latest tag aren't always in sync. Pushed a new tag to both Github and npm with latest code from master

**Comment by dash-** [comment]
Awesome, thanks!  I appreciate you getting to it so quickly.
