### ISSUE TITLE
Dependencies security issues from npm audit

### ISSUE THREAD

**Issue by ganeshkbhat** [zohararad/sails-rest#77]
Some packages are being picked up for security issues. Are you planning to update the deps? There seems to be breaking changes and minor security issues from npm audit. This definitely a package I would love to use.

┌──────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼─────--────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────┤
│ Dependency of │ sails-rest                                                   │
├───────────────┼──────────────────────────────────────────────┤
│ Path          │ sails-rest > lodash                                          │
├───────────────┼──────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼─────-────────────────────────────────────────┤
│ Package       │ negotiator                                                   │
├───────────────┼─────────────────────────-----──────────────────┤
│ Patched in    │ >= 0.6.1                                                     │
├───────────────┼───────────────────────────-──────────────────┤
│ Dependency of │ sails-rest                                                   │
├───────────────┼─────────---───────────────────────────────────┤
│ Path          │ sails-rest > restify > negotiator                            │
├───────────────┼───────────────────────────────────────-──────┤
│ More info     │ https://nodesecurity.io/advisories/106                       │
└───────────────┴─────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼─────────────────────────────────────────────┤
│ Package       │ mime                                                         │
├───────────────┼──────--──────────────────────────────────────┤
│ Patched in    │ >= 1.4.1 < 2.0.0 || >= 2.0.3                                 │
├───────────────┼─────────────────────────────────────────────┤
│ Dependency of │ sails-rest                                                   │
├───────────────┼─────────────────────────────────────────────┤
│ Path          │ sails-rest > superagent > mime                               │
├───────────────┼─────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/535                       │
└───────────────┴─────────────────────────────────────────────┘
┌───────────────┬────────--────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting (XSS)                                   │
├───────────────┼─────────────────────────────────────────────┤
│ Package       │ restify                                                      │
├───────────────┼─────────────────────────────────────────────┤
│ Patched in    │ >=4.1.0                                                      │
├───────────────┼─────────────────────────────────────────────┤
│ Dependency of │ sails-rest                                                   │
├───────────────┼─────────----──────────────────────────────────┤
│ Path          │ sails-rest > restify                                         │
├───────────────┼─────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/314                       │
└───────────────┴─────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────┐
│ Moderate      │ Memory Exposure                                              │
├───────────────┼─────────────────────────────────────────────┤
│ Package       │ tunnel-agent                                                 │
├───────────────┼─────────────────────────────────────────────┤
│ Patched in    │ >=0.6.0                                                      │
├───────────────┼─────────────────────────────────────────────┤
│ Dependency of │ sails-rest                                                   │
├───────────────┼─────────────────────────────────────────────┤
│ Path          │ sails-rest > restify > tunnel-agent                          │
├───────────────┼─────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/598                       │
└───────────────┴─────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼─────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼─────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼─────────────────────────────────────────────┤
│ Dependency of │ sails-postgresql                                             │
├───────────────┼─────────────────────────────────────────────┤
│ Path          │ sails-postgresql > machinepack-postgresql > debug            │
├───────────────┼──────────--──────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴─────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────┐
│ Low           │ Large gzip Denial of Service                                 │
├───────────────┼─────────────────────────────────────────────┤
│ Package       │ superagent                                                   │
├───────────────┼─────────────────────────────────────────────┤
│ Patched in    │ >=3.7.0                                                      │
├───────────────┼─────────────────────────────────────────────┤
│ Dependency of │ sails-rest                                                   │
├───────────────┼──────────--──────────────────────────────────┤
│ Path          │ sails-rest > superagent                                      │
├───────────────┼─────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/479                       │
└───────────────┴──────--──────────────────────────────────────┘

**Comment by zohararad** [comment]
I'm not actively maintaining this package - You're more than welcome to update dependencies and send a PR which I'll accept and merge into master

**Comment by ganeshkbhat** [comment]
Sure. If I face issues or have questions on code, will ping you. Anything that you want me to know as for a styleguide or tests or code writing preferences? This is a nice package. In loopback these are a big breather but there are some other issues. I am also on skype, if you are willing to connect.

**Comment by ganeshkbhat** [comment]
There is one breaking change. Let me take time to get this up

**Comment by zohararad** [comment]
ok - i'll wait to hear from you
